version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"  # Redis server
      - "8001:8001"  # RedisInsight GUI
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  openai-server:
    image: python:3.10-slim
    container_name: openai-compatible-server
    depends_on:
      - redis
    ports:
      - "7009:7009"
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      bash -c "
        pip install -r requirements.txt &&
        python3 server.py
      "
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

volumes:
  redis-data:
    driver: local